_BASE_: "../Base.yaml"

DATASETS:
  TRAIN: ("mpsc_train",)
  TEST: ("mpsc_test",)
  ANNOTATION_ROOT: "./datasets/MPSC/annotation"
  BBOX_DISTRIBUTION_PATH: "./datasets/MPSC/annotation/bbox_distribution.json"
  TEXTSEG_IMG_PATH: "./datasets/TextSeg/image"
  TEXTSEG_ANN_PATH: "./datasets/TextSeg/annotation"


DATALOADER:
  NUM_WORKERS: 4

MODEL:
  WEIGHTS: "output/r_50_poly/pretrain/model_final.pth"  # or the provided pre-trained model
  FP:
    ENABLED: True
    ANNOTATION_PATH: "datasets/MPSC/annotation/train_with_symbol.json"

SOLVER:
  IMS_PER_BATCH: 8
  BASE_LR: 5e-5
  LR_BACKBONE: 5e-6
  WARMUP_ITERS: 0
  STEPS: (16000,)
  MAX_ITER: 10000
  CHECKPOINT_PERIOD: 1000

TEST:
  EVAL_PERIOD: 1000
  DET_ONLY: True

OUTPUT_DIR: "output/r_50_poly/MPSC/finetune"
